project_id = "ijriqmtuyofjymedtjsa"

[functions.send-announcement]
verify_jwt = true

[functions.notify-assessment-completion]
verify_jwt = false

[functions.generate-coach-insights]
verify_jwt = true
